#!/bin/sh
set -eu

mkdir -p scratch
curl -L --fail --silent --show-error \
    -o scratch/encoder.py \
    https://raw.githubusercontent.com/openai/gpt-2/9b63575ef42771a015060c964af2c3da4cf7c8ab/src/encoder.py
